<div class="contentScoreboard">
<div class="leaderboard">
        <h2>🏆 LEADERBOARD 🏆</h2>
        <table>
            <thead>
                <tr>
                    <th>Ranking</th>
                    <th>Team Name</th>
                    <th>Problems Solved</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>
                <?php  $i=0 ; foreach($res as $row){ $i++ ; ?>
                <tr>
                    <td><?= $i ?></td>
                    <td><?= $row["name"] ?></td>
                    <td><?=  $row["ProbSolved"] ?></td>
                    <td><?= $row["Score"] ?></td>
                </tr><?php }?>
            </tbody>
        </table>
    </div>
</div>