<div class="contentScoreboard">
<div class="leaderboard">
        <h2>🏆 LEADERBOARD 🏆</h2>
        <table>
            <thead>
                <tr>
                    <th>Ranking</th>
                    <th>Team Name</th>
                    <th>Problems Solved</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Chorba</td>
                    <td>10</td>
                    <td>250</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>Jelbana</td>
                    <td>9</td>
                    <td>220</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>kosksi</td>
                    <td>8</td>
                    <td>200</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>mermez au poulet</td>
                    <td>7</td>
                    <td>180</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>mermez begri</td>
                    <td>6</td>
                    <td>150</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>mermez kadheb</td>
                    <td>5</td>
                    <td>130</td>
                </tr>
                <tr>
                    <td>7</td>
                    <td>KAFTEJI</td>
                    <td>29</td>
                    <td>1  </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>