<div class="app">
    <video class="bg-video" playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
        <source src="../assets/videos/teaser.mp4" type="video/mp4" />
    </video>
    <div class="content_opacity">
        <div>
            <p class="welcome">Welcome Test Team</p>
            <p class="para">
                Welcome to the challenge where brilliance shines. <br> Your tasks await just below, ready to showcase your skills and creativity? <br> If so, let the competition begin!
                <br><a href="#cards"><button id="start_button">Start now!</button></a>
            </p>
        </div>
        
    </div>
</div>
        <div class="cards" id="cards">
            <div class="card">
                <div class="card_header">
                    Exemple 1
                </div>
                <div class="card_body">
                    <span class="status">Status: <b>Available</b></span>
                    <p>Time: 14:00:00</p>
                    <p>Duration: 3h</p>
                </div>
                <div class="card_footer">
                    <p>Points: <b>100</b></p>
                </div>
            </div>
            <div class="card">
                <div class="card_header">
                    Exemple 2
                </div>
                <div class="card_body">
                    <span class="status">Status: <b>Unavailable</b></span>
                </div>
                <div class="card_footer">
                    <p>Points: <b>150</b></p>
                </div>
            </div>
            <div class="card">
                <div class="card_header">
                    Carta2
                </div>
                <div class="card_body">
                    3awwwwww2
                </div>
                <div class="card_footer">
                    3awwwwww2
                </div>
            </div>
            <div class="card">
                <div class="card_header">
                    Carta2
                </div>
                <div class="card_body">
                    3awwwwww2
                </div>
                <div class="card_footer">
                    3awwwwww2
                </div>
            </div>
            <div class="card">
                <div class="card_header">
                    Carta2
                </div>
                <div class="card_body">
                    3awwwwww2
                </div>
                <div class="card_footer">
                    3awwwwww2
                </div>
            </div>
        </div>