<div class="app">
    <video class="bg-video" playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
        <source src="../assets/videos/teaser.mp4" type="video/mp4" />
    </video>
    <div class="content_opacity">
        <div>
            <p class="welcome">Welcome Test Team</p>
            <p class="para">
                Welcome to the challenge where brilliance shines. <br> Your tasks await just below, ready to showcase your skills and creativity? <br> If so, let the competition begin!
                <br><a href="#cards"><button id="start_button">Start now!</button></a>
            </p>
        </div>
        
    </div>
</div>
<div class="cards" id="cards">
    <?php
        foreach($open_problems as $prblm){?>
            <div class="card">
            <?php if ($prblm["IsCompleted"] == 0){?>
                <a style="text-decoration:none;color:white" href="../ProblemPage?id=<?=$prblm["id"]?>&name=<?=$prblm["name"]?>&time=<?=substr($prblm["DateOpen"],11)?>&Duration=<?=$prblm["Duration"]?>&points=<?=$prblm["points"]?>">
                <?php } ?>
                <div class="card_header">
                    <?= $prblm["name"]?>
                </div>
                <div class="card_body">
                    <span class="status">Status: <b><?= ($prblm["IsCompleted"])? "Expired" : "Available"?></b></span>
                <p>Time: <?= substr($prblm["DateOpen"],11)?></p>
                    <p>Duration: <?=$prblm["Duration"]."h" ?></p>
                </div>
                <div class="card_footer">
                    <p>Points: <b><?= $prblm["points"]?></b></p>
                </div>
                </a>
            </div>
    <?php }?>