<div class="app">
    <video class="bg-video" playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
        <source src="../assets/videos/teaser.mp4" type="video/mp4" />
    </video>
    <div class="content_opacity">
        <div>
            <p class="welcome">Welcome Our Juries</p>
            <p class="para">
                It is a pleasure to have you with us for this event. We truly appreciate your presence <br> and your support. We hope you have a wonderful time with us,<br> and thank you for being here!
            </p>
        </div>
        <div class="btns">
            <a href="../AddExemple/"> <button>
                    Add Example
                </button></a>
            <a href="../showExample/">
                <button>
                    Show Examples
                </button></a>
            <a href="../Evaluate/">
                <button>
                    Evaluate Examples
                </button></a>
            <a href="../scoreboard/">
                <button>
                    Show ScoreBoard
                </button></a>
        </div>
    </div>
</div>