<div class="problemPageContainer">
    <div class="leftBox"></div>
    <div class="rightBox">
        <form action="index.php" class="ProblemForm">
        <fieldset class="fieldset" style="text-align:center">
            <legend><p style="text-align:center;font-size: 25px;margin-top: 10px;margin-right:10px">Exemple 1</p></legend>
            <br>
            <p>Points: <b>100</b></p>
            <p>Time: <b>14:00:00</b></p>
            <p>Duration: <b>1.30h</b></p>
            <input type="file" name="file" style="border: none">
            <input type="submit" value="SUBMIT" class="submit-btn" name="submit">
            </fieldset>
        </form>
    </div>
</div>