<div class="problemPageContainer">
    <div class="leftBox"></div>
    <div class="rightBox">
        <div class="submitForm">
            <p class="problemTitle">Example 1</p>
            <div class="problemData">
            <p class="problemInfo">Points: <b>100</b></p>
            <p class="problemInfo">Time: <b>14:00:00</b></p>
            <p class="problemInfo">Duration: <b>3h</b></p>
            <input type="file" name="file">
            <button class="submit" name="submit">Submit</button>
            </div>
            </div>
        </div>
    </div>
</div>